import sys
import json
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from dotenv import load_dotenv

load_dotenv()

from src.orchestrator.pipeline import run_pipeline
from src.arxiv_search import search_arxiv
from src.__init__ import get_client, get_model

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

REPORT_PROMPT = """You are a research advisor. Based on the following analysis of {num_papers} papers on a related topic, produce a concise report.

Paper summaries and cross-paper synthesis are provided below.

{analysis_json}

Your task: produce a JSON with three sections:

1. "executive_summary": A 2-3 paragraph synthesis of the research landscape.

2. "deep_dive_recommendations": A ranked list of which papers to study more deeply, with reasons. Recommend 1-3 papers.
   Format: [{{"paper": "title", "reason": "why this paper deserves close study", "key_question": "one open question this paper raises"}}, ...]

3. "further_search_queries": 2-3 search queries to find additional related papers on arXiv (e.g. specific sub-topics or techniques that emerged from the analysis).

Return ONLY valid JSON."""


def _call_llm(prompt):
    client = get_client()
    model = get_model()
    resp = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=4000,
    )
    return resp.choices[0].message.content


def _add_heading(doc, text, level=1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)


def _add_bullets(doc, items):
    for item in items:
        if isinstance(item, dict):
            for k, v in item.items():
                doc.add_paragraph(f"{k}: {v}", style="List Bullet")
        else:
            doc.add_paragraph(str(item), style="List Bullet")


def _add_table(doc, headers, rows):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = "Light Grid Accent 1"
    for i, h in enumerate(headers):
        table.rows[0].cells[i].text = h
    for r, row in enumerate(rows):
        for c, val in enumerate(row):
            table.rows[r + 1].cells[c].text = str(val)
    doc.add_paragraph()


def generate_report(result, output_path, search_query=None):
    doc = Document()

    # Title
    title = doc.add_heading("Literature Review Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    papers = result.get("papers", [])
    failed = result.get("failed", [])
    synthesis = result.get("synthesis", {})

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    n_ok = len(papers)
    n_fail = len(failed)
    meta.add_run(f"Papers analyzed: {n_ok}").font.size = Pt(11)
    if n_fail:
        meta.add_run(f", {n_fail} failed").font.size = Pt(11)
    meta.add_run("\nGenerated by OpenCode Research Agent").font.size = Pt(10)
    meta.add_run().add_break()

    if n_fail:
        _add_heading(doc, "Failed URLs", level=1)
        for f in failed:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(f["url"]).bold = True
            p.add_run(f"  — {f['error']}")

    if not papers:
        doc.add_paragraph("No papers were successfully processed. Report cannot be generated.")
        doc.save(output_path)
        print(f"Report saved to {output_path} (no successful papers)")
        return output_path

    # Executive Summary
    _add_heading(doc, "Executive Summary", level=1)
    es = synthesis.get(
        "executive_synthesis",
        synthesis.get("cross_paper_comparison", {}).get("methodology_comparison", ""),
    )
    doc.add_paragraph(es)

    if synthesis.get("key_insights"):
        _add_heading(doc, "Key Insights", level=2)
        _add_bullets(doc, synthesis["key_insights"])

    # Paper Summaries
    _add_heading(doc, "Paper Summaries", level=1)
    for i, paper in enumerate(papers):
        _add_heading(doc, f"{i+1}. {paper.get('title', 'Untitled')}", level=2)
        meta_text = paper.get("metadata", {})
        if meta_text.get("authors"):
            doc.add_paragraph(f"Authors: {', '.join(meta_text['authors'][:5])}")
        if meta_text.get("year"):
            doc.add_paragraph(f"Year: {meta_text['year']}")
        doc.add_paragraph(f"Core Idea: {paper.get('core_idea', '')}")
        if paper.get("key_results"):
            _add_heading(doc, "Key Results", level=3)
            _add_bullets(doc, paper["key_results"])
        if paper.get("novelty"):
            doc.add_paragraph(f"Novelty: {paper['novelty']}")
        doc.add_paragraph()  # spacing

    # Cross-Paper Analysis
    _add_heading(doc, "Cross-Paper Analysis", level=1)
    comp = synthesis.get("cross_paper_comparison", {})
    if (
        comp.get("similarities")
        and comp["similarities"][0]
        != "Only one paper provided; no cross-paper comparison possible."
    ):
        _add_heading(doc, "Similarities", level=2)
        _add_bullets(doc, comp["similarities"])
    if (
        comp.get("differences")
        and comp["differences"][0]
        != "Only one paper provided; no cross-paper comparison possible."
    ):
        _add_heading(doc, "Differences", level=2)
        _add_bullets(doc, comp["differences"])
    if (
        comp.get("contradictions")
        and comp["contradictions"][0]
        != "No contradictions as only one paper is evaluated."
    ):
        _add_heading(doc, "Contradictions", level=2)
        _add_bullets(doc, comp["contradictions"])

    if synthesis.get("practical_takeaways"):
        _add_heading(doc, "Practical Takeaways", level=2)
        _add_bullets(doc, synthesis["practical_takeaways"])

    # Deep-Dive Recommendations (LLM-generated)
    _add_heading(doc, "Deep-Dive Recommendations", level=1)
    analysis_json = json.dumps({"papers": papers, "synthesis": synthesis}, indent=2)
    prompt = REPORT_PROMPT.format(num_papers=len(papers), analysis_json=analysis_json)
    try:
        llm_out = _call_llm(prompt)
        llm_out = llm_out.strip()
        if llm_out.startswith("```"):
            lines = [l for l in llm_out.split("\n") if not l.startswith("```")]
            llm_out = "\n".join(lines)
        recs = json.loads(llm_out)
        exec_sum = recs.get("executive_summary", "")
        if exec_sum:
            _add_heading(doc, "Research Landscape", level=2)
            doc.add_paragraph(exec_sum)
        deep_dive = recs.get("deep_dive_recommendations", [])
        if deep_dive:
            _add_table(
                doc,
                ["Paper", "Why Deep-Dive", "Key Question"],
                [
                    [d.get("paper", ""), d.get("reason", ""), d.get("key_question", "")]
                    for d in deep_dive
                ],
            )
        search_queries = recs.get("further_search_queries", [])
    except (json.JSONDecodeError, KeyError) as e:
        doc.add_paragraph(f"(Could not generate LLM recommendations: {e})")
        search_queries = []

    # Suggested Further Reading — from arXiv
    _add_heading(doc, "Suggested Further Reading", level=1)
    queries_to_run = search_queries or [search_query] if search_query else []
    if not queries_to_run:
        titles = [p.get("title", "") for p in papers]
        queries_to_run = [t.split(". ")[0][:80] for t in titles[:2]]
    seen_links = set()
    for q in queries_to_run:
        if not q:
            continue
        _add_heading(doc, f'Search: "{q}"', level=2)
        try:
            results = search_arxiv(q, max_results=4)
        except Exception as e:
            doc.add_paragraph(f"(arXiv search unavailable: {e})")
            continue
        for r in results:
            if r["link"] in seen_links:
                continue
            seen_links.add(r["link"])
            p = doc.add_paragraph()
            p.add_run(r["title"]).bold = True
            p.add_run(f'\nAuthors: {", ".join(r["authors"])}')
            p.add_run(f'\nAbstract: {r["abstract"][:300]}...')
            p.add_run(f'\nLink: {r["link"]}')
            p.add_run().add_break()

    # Appendix
    _add_heading(doc, "Appendix: Papers Processed", level=1)
    _add_table(
        doc,
        ["#", "Title", "URL"],
        [
            [str(i + 1), p.get("title", "?"), p.get("url", "?")]
            for i, p in enumerate(papers)
        ],
    )

    doc.save(output_path)
    print(f"Report saved to {output_path}")
    return output_path


def main():
    parser = argparse.ArgumentParser(
        description="Generate a literature review Word report"
    )
    parser.add_argument(
        "input", type=str, help="Input file with paper URLs (one per line, or JSON)"
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        default="literature_review.docx",
        help="Output .docx file",
    )
    parser.add_argument(
        "--search",
        "-s",
        type=str,
        default=None,
        help="Optional arXiv search query for related papers",
    )
    args = parser.parse_args()

    # Read input file
    raw = Path(args.input).read_text().strip()
    if raw.startswith("{"):
        data = json.loads(raw)
        urls = data.get("papers", data.get("urls", []))
        args.search = args.search or data.get("search_query")
    else:
        urls = [
            line.strip()
            for line in raw.split("\n")
            if line.strip() and not line.startswith("#")
        ]

    if not urls:
        print("No paper URLs found in input file.")
        sys.exit(1)

    print(f"Processing {len(urls)} papers...")
    result = run_pipeline(urls)
    generate_report(result, args.output, search_query=args.search)


if __name__ == "__main__":
    main()
